<td>$row['form7a_id']</td>
<td>$row['form7a_natureOfCredit']</td>
<td>$row['form7a_notionalLimitSanctionDate']</td>
<td>$row['form7a_notionalLimitAmount']</td>
<td>$row['form7a_notionalLimitExpiry']</td>
<td>$row['form7a_sanctioningAuthority']</td>
<td>$row['form7a_lcDate']</td>
<td>$row['form7a_lcTenor']</td>
<td>$row['form7a_lcValueFc']</td>
<td>$row['form7a_lcValueBdt']</td>
<td>$row['form7a_lcMarginPercentage']</td>
<td>$row['form7a_dateDocumentReceivedInBranch']</td>
<td>$row['form7a_documentValue']</td>
<td>$row['form7a_lodgementDate']</td>
<td>$row['form7a_dateDiscrepencyNotice']</td>
<td>$row['form7a_dueDate']</td>
<td>$row['form7a_acceptancePaymentDate']</td>
<td>$row['form7a_padCreatoionDate']</td>
<td>$row['form7a_padAmount']</td>
<td>$row['form7a_sourceOfAdjustment']</td>
<td>$row['form7a_billEntryMatchingDate']</td>
<td>$row['form7a_amountSinceeAdjusted']</td>
<td>$row['form7a_presentOutstanding']</td>
<td>$row['form7a_forcedLoanCreationDate']</td>
<td>$row['form7a_forcedLoanCreationReason']</td>
<td>$row['form7a_classificationStatus']</td>
<td>$row['form7a_litigableAmount']</td>

